name: Deploy Frontend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2
          role-session-name: GitHubActionsSession
          audience: sts.amazonaws.com

      - name: Get SSM Parameters
        run: |
          echo "S3_BUCKET=$(aws ssm get-parameter --name /jrde15/frontend/s3-bucket --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=$(aws ssm get-parameter --name /jrde15/frontend/cloudfront-distribution-id --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "API_ENDPOINT=$(aws ssm get-parameter --name /jrde15/frontend/api-endpoint --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "API_KEY=$(aws ssm get-parameter --name /jrde15/frontend/api-key --with-decryption --query Parameter.Value --output text)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_API_ENDPOINT: ${{ env.API_ENDPOINT }}
          VITE_API_KEY: ${{ env.API_KEY }}

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://${{ env.S3_BUCKET }}/ --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 
